AC-19 added a example request to a station to query properties
Diplomarbeit-PGHFP-2024-2025/ac-car pull request #7
Opened 2024-11-13 10:17 UTC by JonasPfeifer05

2024-11-13 10:18 UTC, leToxic approved these changes
lgtm

2024-11-13 11:23 UTC, ToBinio requested changes

2024-11-13 11:23 UTC, ToBinio commented on justfile
> +all:
dont do that. These are not things you always want to run

you can add a build & run if you want but you dont want to isntall deps everytime and fix lints...

2024-11-14 06:56 UTC, xFizzar requested changes

2024-11-14 06:56 UTC, xFizzar commented on justfile
> +    python3 -m pip install uagents==0.17.0
why not 0.17.1

2024-11-14 08:00 UTC, xFizzar approved these changes
lgtm

2024-11-14 08:02 UTC, ToBinio approved these changes

2024-11-14 08:17 UTC, merged